import Header from './Component/Header/Header.jsx';
import Footer from './Component/Footer/Footer.jsx';
import { CountProvider } from './Context/CartContext.js';

export const metadata = {
  title: 'Casual Store',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (

    <html lang="en">

      <body style={{ margin: 0, padding: 0 }}>
        <CountProvider>
          <Header />

          {children}
        </CountProvider>
        <Footer />
      </body>

    </html>

  )
}
